%%%
  VERSION:1
  LANGUAGE:ENGLISH
%%%

MODULE mAUTODESK

  ! Global Work Object + Tool (define ONCE here)
  PERS wobjdata wADSK0:=[FALSE,TRUE,"", [[1587.651,1696.886,784.6553],[0.0162324,0.0011719,-0.0014062,-0.9998666]],[[0,0,0],[1,0,0,0]]];
  PERS tooldata tADSK27:=[TRUE,[[-244.295, -0.232878, 212.8031],[0.7071068,0,-0.707168,0]],[40,[50,0,120],[1,0,0,0],0,0,0]];

  ! Speeds
  PERS speeddata v75:=[75,500,5000,1000];
  PERS speeddata v800:=[800,500,5000,1000];
  PERS speeddata v25:=[25,500,5000,1000];

  PROC main()
    ! Generated by AUTODESK Fusion CAM 2605.1.52
    ! Creation date: 2026-01-20 4:08:45 p.m.

    ! Acceleration and jerk/ramp (percentage)
    AccSet 20,20;

    ! Configurations
    ConfJ\On;
    ConfL\Off;

    ! Load Tool
    !Tool_Change tADSK27;

    ! Spindle On/Speed
    ! Spindle_ON 16500;

    ! Move to start position ONCE (removed from each contour PROC)
    MoveAbsJ [[0,0,5,-70,40,70],[9E9,9E9,9E9,9E9,9E9,9E9]]\NoEOffs,v800,fine,tADSK27;

    p2D_Contour22;
    p2D_Contour23;
    p2D_Contour24;
    p2D_Contour25;

    ! Spindle OFF
    ! SetDO Local_IO_0_DO11, 0;
    WaitTime 5;

    ConfJ\On;
    ConfL\On;
    Stop;
  ENDPROC

ENDMODULE
