%%%
  VERSION:1
  LANGUAGE:ENGLISH
%%%

MODULE mAUTODESK

  PERS speeddata v114:=[350,500,5000,1000];
  PERS speeddata v17:=[200,500,5000,1000];
  PERS speeddata v38:=[250,500,5000,1000];

  PROC main()
    ! Generated by AUTODESK Fusion CAM 2605.1.52
    ! Creation date: 2026-01-19 4:13:47 p.m.

    ! Acceleration and jerk/ramp (percentage)
    AccSet 20,20;

    ! Configurations
    ConfJ\On;
    ConfL\Off;

    ! Load Tool
    !Tool_Change tADSK27;

    ! Spindle On/Speed
    !Spindle_ON 15000;

    p2D_Contour_3_8;

    ! Spindle Off
    !Spindle_OFF;

    ConfJ\On;
    ConfL\On;
    Stop;
  ENDPROC
ENDMODULE
